"""AmbientEngine — deterministic, opt-in proactive scheduler.

For each channel with `ambient_enabled`, fire one backend-generated check-in per
`ambient_interval_hours`, with a hard per-channel cooldown tracked in settings. The
DECISION to speak is purely time-based (deterministic) — no LLM relevance gate in
this version (that's a v1 research item, see TODO.md). The content is generated by
the channel's backend and suppressed if the model returns SKIP.
"""
from __future__ import annotations

import asyncio
import time

from agent_tag.core.orchestrator import TurnOrchestrator
from agent_tag.store.base import Store

_LAST_PREFIX = "ambient_last:"


class AmbientEngine:
    def __init__(
        self,
        store: Store,
        orchestrator: TurnOrchestrator,
        senders: dict,
        *,
        tick_seconds: float = 300.0,
        now=time.time,
    ) -> None:
        self.store = store
        self.orch = orchestrator
        self.senders = senders
        self.tick_seconds = tick_seconds
        self._now = now

    def _due(self, channel_id: str, interval_hours: int) -> bool:
        last = self.store.get_setting(_LAST_PREFIX + channel_id)
        now = self._now()
        if last is None:
            # first time we see it enabled: start the clock, don't fire immediately
            self.store.set_setting(_LAST_PREFIX + channel_id, str(now))
            return False
        return (now - float(last)) >= interval_hours * 3600

    async def tick(self) -> int:
        """One scheduling pass. Returns number of ambient messages sent."""
        sent = 0
        for channel in self.store.list_channels():
            policy = self.store.get_policy(channel.id)
            if policy is None or not policy.ambient_enabled:
                continue
            if channel.platform not in self.senders:
                continue
            if not self._due(channel.id, policy.ambient_interval_hours):
                continue
            try:
                fired = await self.orch.proactive_check_in(channel, self.senders)
            except Exception:  # noqa: BLE001 - never let one channel break the loop
                fired = False
            # update cooldown regardless, so a quiet channel doesn't retry every tick
            self.store.set_setting(_LAST_PREFIX + channel.id, str(self._now()))
            if fired:
                sent += 1
        return sent

    async def run(self, stop: asyncio.Event) -> None:
        while not stop.is_set():
            try:
                await self.tick()
            except Exception:  # noqa: BLE001
                pass
            try:
                await asyncio.wait_for(stop.wait(), timeout=self.tick_seconds)
            except asyncio.TimeoutError:
                pass
